// --------------------------------------------------------------
// Copyright 2026 CyberAgent, Inc.
// --------------------------------------------------------------

#nullable enable

using AudioConductor.Core.Models;
using AudioConductor.Editor.Core.Models;
using AudioConductor.Editor.Core.Tests;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using Object = UnityEngine.Object;

namespace AudioConductor.Editor.Core.Tools.CodeGen.Tests
{
    internal class CueEnumGeneratorTests
    {
        private const string RootFolder = "Assets/gen/" + nameof(CueEnumGeneratorTests);
        private CueSheetAsset _asset = null!;
        private AudioConductorEditorSettings _settings = null!;

        [SetUp]
        public void SetUp()
        {
            if (AssetDatabase.IsValidFolder(RootFolder))
                AssetDatabase.DeleteAsset(RootFolder);
            Utility.CreateFolderRecursively(RootFolder);

            _settings = ScriptableObject.CreateInstance<AudioConductorEditorSettings>();
            _settings.defaultCodeGenNamespace = "Project.Generated";
            _settings.defaultCodeGenClassSuffix = "ProjectIds";
            AssetDatabase.CreateAsset(_settings, RootFolder + "/AudioConductorEditorSettings.asset");
            AssetDatabase.Refresh();

            _asset = ScriptableObject.CreateInstance<CueSheetAsset>();
            _asset.cueSheet.name = "BGM";
            _asset.useDefaultCodeGenOutputPath = false;
            _asset.useDefaultCodeGenNamespace = false;
            _asset.useDefaultCodeGenClassSuffix = false;
        }

        [TearDown]
        public void TearDown()
        {
            if (AssetDatabase.IsValidFolder(RootFolder))
                AssetDatabase.DeleteAsset(RootFolder);

            Object.DestroyImmediate(_asset);
            if (_settings != null)
                Object.DestroyImmediate(_settings, true);
        }

        [Test]
        public void Generate_EmptyCueList_ReturnsSuccessWithEmptyEnum()
        {
            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.True);
            Assert.That(result.SourceCode, Does.Contain("public enum BGM"));
            Assert.That(result.Errors, Is.Empty);
        }

        [Test]
        public void Generate_WithCues_ContainsExpectedMembers()
        {
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });
            _asset.cueSheet.cueList.Add(new Cue { name = "battle", cueId = 2 });
            _asset.cueSheet.cueList.Add(new Cue { name = "game_over", cueId = 3 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.True);
            Assert.That(result.SourceCode, Does.Contain("Title = 1,"));
            Assert.That(result.SourceCode, Does.Contain("Battle = 2,"));
            Assert.That(result.SourceCode, Does.Contain("GameOver = 3,"));
        }

        [Test]
        public void Generate_WithAutoGeneratedHeader()
        {
            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.StartWith("// <auto-generated/>"));
        }

        [Test]
        public void Generate_WithNamespace_WrapsInNamespace()
        {
            _asset.codeGenNamespace = "AudioConductor.Generated";
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.True);
            Assert.That(result.SourceCode, Does.Contain("namespace AudioConductor.Generated"));
            Assert.That(result.SourceCode, Does.Contain("    public enum BGM"));
        }

        [Test]
        public void Generate_WithoutNamespace_NoNamespaceWrapper()
        {
            _asset.codeGenNamespace = string.Empty;
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Not.Contain("namespace "));
            Assert.That(result.SourceCode, Does.Contain("public enum BGM"));
        }

        [Test]
        public void Generate_WithCustomSuffix_UsesCustomSuffix()
        {
            _asset.codeGenClassSuffix = "AudioIds";

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Contain("public enum BGMAudioIds"));
        }

        [Test]
        public void Generate_UseDefaultNamespace_UsesEditorSettingsValue()
        {
            _asset.useDefaultCodeGenNamespace = true;
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.True);
            Assert.That(result.SourceCode, Does.Contain("namespace Project.Generated"));
        }

        [Test]
        public void Generate_UseDefaultClassSuffix_UsesEditorSettingsValue()
        {
            _asset.useDefaultCodeGenClassSuffix = true;

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.True);
            Assert.That(result.SourceCode, Does.Contain("public enum BGMProjectIds"));
        }

        [Test]
        public void Generate_DuplicateCueName_ReturnsFailureWithError()
        {
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 2 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.False);
            Assert.That(result.Errors, Has.Count.GreaterThan(0));
        }

        [Test]
        public void Generate_IdentifierCollisionAfterConversion_ReturnsFailureWithError()
        {
            // "hello_world" and "hello-world" both convert to "HelloWorld"
            _asset.cueSheet.cueList.Add(new Cue { name = "hello_world", cueId = 1 });
            _asset.cueSheet.cueList.Add(new Cue { name = "hello-world", cueId = 2 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.False);
            Assert.That(result.Errors, Has.Count.GreaterThan(0));
        }

        [Test]
        public void Generate_EnumName_MatchesCueSheetName()
        {
            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.EnumName, Is.EqualTo("BGM"));
        }

        [Test]
        public void Generate_EmptyCueSheetName_FallsBackToAssetName()
        {
            _asset.cueSheet.name = string.Empty;
            _asset.name = "SampleCueSheet";

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.Success, Is.True);
            Assert.That(result.SourceCode, Does.Contain("public enum SampleCueSheet"));
        }

        [Test]
        public void Generate_WithCues_ContainsExtensionClass()
        {
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });
            _asset.cueSheet.cueList.Add(new Cue { name = "battle", cueId = 2 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Contain("public static class BGMExtensions"));
        }

        [Test]
        public void Generate_WithCues_ExtensionMethodUsesSwitch()
        {
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });
            _asset.cueSheet.cueList.Add(new Cue { name = "battle", cueId = 2 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Contain("public static string GetCueSheetName(this BGM value)"));
            Assert.That(result.SourceCode, Does.Contain("BGM.Title => cueSheetName,"));
            Assert.That(result.SourceCode, Does.Contain("BGM.Battle => cueSheetName,"));
            Assert.That(result.SourceCode, Does.Contain("_ => throw new ArgumentOutOfRangeException"));
        }

        [Test]
        public void Generate_WithNamespace_ExtensionClassWrappedInNamespace()
        {
            _asset.codeGenNamespace = "AudioConductor.Generated";
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Contain("public static class BGMExtensions"));
            Assert.That(result.SourceCode, Does.Contain("GetCueSheetName"));
        }

        [Test]
        public void Generate_EmptyCueList_DoesNotContainExtensionClass()
        {
            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Not.Contain("Extensions"));
        }

        [Test]
        public void Generate_WithCustomSuffix_ExtensionClassUsesFullEnumName()
        {
            _asset.codeGenClassSuffix = "AudioIds";
            _asset.cueSheet.cueList.Add(new Cue { name = "title", cueId = 1 });

            var result = CueEnumGenerator.Generate(_asset);

            Assert.That(result.SourceCode, Does.Contain("public static class BGMAudioIdsExtensions"));
            Assert.That(result.SourceCode, Does.Contain("this BGMAudioIds value"));
        }
    }
}
