// --------------------------------------------------------------
// Copyright 2026 CyberAgent, Inc.
// --------------------------------------------------------------

#nullable enable

using System.Collections.Generic;
using System.Text;
using AudioConductor.Core.Models;
using AudioConductor.Editor.Core.Tools.Shared;

namespace AudioConductor.Editor.Core.Tools.CodeGen
{
    internal static class CueEnumGenerator
    {
        /// <summary>
        ///     Generates C# enum source code from the cueList of the given CueSheetAsset.
        /// </summary>
        internal static GenerationResult Generate(CueSheetAsset asset)
        {
            var errors = new List<string>();
            var cueList = asset.cueSheet.cueList;
            var settings = AudioConductorEditorSettingsRepository.instance.Settings;
            var resolvedSettings = CueEnumCodeGenSettingsResolver.Resolve(asset, settings);

            var baseName = !string.IsNullOrEmpty(asset.cueSheet.name) ? asset.cueSheet.name : asset.name;

            var enumName = IdentifierConverter.ToPascalCase(baseName) + resolvedSettings.ClassSuffix;

            // Validate cue names and cache converted identifiers
            var seenNames = new HashSet<string>();
            var seenIdentifiers = new HashSet<string>();
            var identifiers = new string[cueList.Count];

            for (var i = 0; i < cueList.Count; i++)
            {
                var cue = cueList[i];
                if (!seenNames.Add(cue.name))
                    errors.Add($"Duplicate cue name: \"{cue.name}\"");

                var identifier = IdentifierConverter.ToPascalCase(cue.name);
                identifiers[i] = identifier;
                if (!seenIdentifiers.Add(identifier))
                    errors.Add($"Identifier collision after conversion: \"{identifier}\" (from \"{cue.name}\")");
            }

            if (errors.Count > 0)
                return new GenerationResult(false, string.Empty, string.Empty, errors);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");

            if (cueList.Count > 0)
                sb.AppendLine("using System;");

            var hasNamespace = !string.IsNullOrEmpty(resolvedSettings.Namespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {resolvedSettings.Namespace}");
                sb.AppendLine("{");
                AppendEnum(sb, enumName, cueList, identifiers, "    ");
                if (cueList.Count > 0)
                {
                    sb.AppendLine();
                    AppendExtensionClass(sb, enumName, baseName, cueList, identifiers, "    ");
                }

                sb.AppendLine("}");
            }
            else
            {
                AppendEnum(sb, enumName, cueList, identifiers, "");
                if (cueList.Count > 0)
                {
                    sb.AppendLine();
                    AppendExtensionClass(sb, enumName, baseName, cueList, identifiers, "");
                }
            }

            var sourceCode = sb.ToString();

            return new GenerationResult(true, sourceCode, enumName, errors);
        }

        private static void AppendEnum(StringBuilder sb, string enumName, IReadOnlyList<Cue> cueList,
            string[] identifiers, string indent)
        {
            sb.AppendLine($"{indent}public enum {enumName}");
            sb.AppendLine($"{indent}{{");
            for (var i = 0; i < cueList.Count; i++)
                sb.AppendLine($"{indent}    {identifiers[i]} = {cueList[i].cueId},");
            sb.AppendLine($"{indent}}}");
        }

        private static void AppendExtensionClass(StringBuilder sb, string enumName, string cueSheetName,
            IReadOnlyList<Cue> cueList, string[] identifiers, string indent)
        {
            sb.AppendLine($"{indent}public static class {enumName}Extensions");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static string GetCueSheetName(this {enumName} value)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        const string cueSheetName = \"{cueSheetName}\";");
            sb.AppendLine($"{indent}        return value switch");
            sb.AppendLine($"{indent}        {{");
            for (var i = 0; i < cueList.Count; i++)
                sb.AppendLine($"{indent}            {enumName}.{identifiers[i]} => cueSheetName,");
            sb.AppendLine(
                $"{indent}            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),");
            sb.AppendLine($"{indent}        }};");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
        }

        internal readonly struct GenerationResult
        {
            internal bool Success { get; }
            internal string SourceCode { get; }
            internal string EnumName { get; }
            internal IReadOnlyList<string> Errors { get; }

            internal GenerationResult(bool success, string sourceCode, string enumName,
                IReadOnlyList<string> errors)
            {
                Success = success;
                SourceCode = sourceCode;
                EnumName = enumName;
                Errors = errors;
            }
        }
    }
}
